### ISSUE TITLE
Blurry images - seems to be caused by BeginImageContext

### ISSUE THREAD

**Issue by leenyburger** [mustangostang/UIImage-ResizeMagick#14]
The images are rendering blurry on my iPhone 5s after being resized.  To fix this problem I changed the drawImageInBounds and croppedImagewithRect methods.  I had to change the UIGraphicsBeginImageContext line to  UIGraphicsBeginImageContextWithOptions(bounds.size,YES,0);

**Comment by timbodeit** [comment]
This is handled by #7
