### ISSUE TITLE
Create new release + new podspec

### ISSUE THREAD

**Issue by paulosoaresvieira** [mustangostang/UIImage-ResizeMagick#17]
is it possible to create a new podspec and release a new version? 

thanks

**Comment by aelam** [comment]
No choice.  You can use UIImage-ResizeMagick@NoWarnings first 

-> UIImage-ResizeMagick@NoWarnings (0.0.2)
   Resizing UIImage on iOS. ImageMagick-style.
   pod 'UIImage-ResizeMagick@NoWarnings', '~> 0.0.2'
   - Homepage: https://github.com/EmoneyCN/UIImage-ResizeMagick
   - Source:   https://github.com/EmoneyCN/UIImage-ResizeMagick.git
   - Versions: 0.0.2 [master repo]
